Adding Navbar and Banner
Feliperto/PortfolioWebsite-Microverse pull request #1
Opened 2023-05-31 21:56 UTC by Feliperto

In this pull request i've created the structure of my portfolio website and then i added some stylings.

2023-05-31 22:28 UTC, AbdusSattar-70 reviewed
Hi @Feliperto, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that appears that your submitted project does not align with the Microverse suggested [README template](https://github.com/microverseinc/readme-template), as all main headers should be present in your repository. To ensure compliance, please ensure that you utilize the recommended readme template provided by Microverse. 

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-05-31 22:39 UTC, Feliperto commented
Hello @AbdusSattar-70, can i only let in the "getting started" header the sub-header of set up and delete the others
?

2023-05-31 22:42 UTC, Feliperto commented
And i have a problem whit the website, when i load my page in github pages the background images don't appear, the message in the console is this "Failed to load resource: the server responded with a status of 404 ()". Do you know what is it?
@AbdusSattar-70

2023-06-01 14:42 UTC, stanleySimeon requested changes
# Hi @Feliperto, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![](https://media4.giphy.com/media/fQfSfrABMzaGMI6PR2/giphy-downsized.gif?cid=29caca75qwcits9occdq81bml1vhvhn8dlwhehk1zqhtslxc&ep=v1_gifs_search&rid=giphy-downsized.gif&ct=g)

## Highlights
- Correct use of Gitflow ✔️
- Linter checks are passed ✔️
- Good PR description ✔️
- Meaningful commit messages ✔️


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- you stick to the design as much as possible.
- adding background images, to follow the Figma design.

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-01 14:42 UTC, stanleySimeon commented on index.html
> +            <h2 class="navbar__logo">Logo</h2>
Kindly I suggest you make sure the logo has a link `a` tag to make your project more professional and easy to use. 😄

2023-06-01 14:42 UTC, stanleySimeon commented on index.html
> +            <h2 class="navbar__logo">Logo</h2>
- Kindly I suggest you make sure the logo has a link `a` tag.
This is for three reasons: convention, semantics, and user experience(UX). [Check this link](https://ux.stackexchange.com/questions/81727/why-is-it-standard-for-a-website-logo-to-navigate-to-the-home-page) for more info. 😄
- Also I suggest you remove the logo inside the `nav` tag.

2023-06-01 14:42 UTC, stanleySimeon commented on index.html
> +            </div>
Kindly I suggest you use `ul` and `li` tags instead of a `div` to follow HTML's good semantics and best practices. 😄

2023-06-01 14:42 UTC, stanleySimeon commented on index.html
> +        <div class="main__container">
Kindly make sure the container is a `section` tag to follow HTML best practices and good semantics. 😄

2023-06-01 14:42 UTC, stanleySimeon commented on index.html
> +            </spam>
I think there is a misspelling here, kindly correct this to be `span` instead of **spam**. 😄

2023-06-01 14:42 UTC, stanleySimeon commented on index.html
> +        </div>
As mentioned above, kindly I suggest you use a `ul` tag for the list of icons to group them, and `li` per icon, and each icon has a link (`a` tag) to follow HTML good semantics. 😄

2023-06-01 15:48 UTC, binhussen approved these changes
Hi @Feliperto , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉
<img src="https://user-images.githubusercontent.com/65852621/133696182-6c5b784b-0083-427a-b24d-3ec870915f79.jpg"/>
## Highlights
- Fixed Request Changes ✔️
- Sticked given Design ✔️
- Well Structured Code ✔️
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-01 17:19 UTC, merged