Add local storage
Feliperto/PortfolioWebsite-Microverse pull request #12
Opened 2023-06-22 22:12 UTC by Feliperto

In tis branch i used js to add localstorage to my project, so when the user type his name and mail in the form and recharge the website his data will be there

2023-06-22 23:01 UTC, addod19 requested changes
### Hi @Feliperto and @Godedict, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
- [ ] Correct GitHub flow followed  :fireworks: 
- [ ] README file is professional and has all the relevant headers :rocket: 
- [ ] The contact form information is persistent to page reloads :fireworks: 
- [ ] After filling the form, and not submitting it, the entered values should be saved in the browser :+1: 
- [ ] When visiting the page the form inputs should be contained, be auto-populated with, the values entered in the previous visit to the page :100: 
- [ ] If at the previous visit to the page, in the same browser, no input was entered in the form then the form inputs should remain empty :fireworks: 


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- Capitalizing all commit messages :man_technologist: 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-22 23:01 UTC, addod19 commented on js/main.js
> +        localStorage.setItem('email', email)
- [ ] It would  be better if we store the data as objects instead of creating one local storage entry per input field as we have currently. Here is how we can improve on it as seen below. We should capture all inputs in the form
```
const form = {
  let name = document.getElementById('name').value;
  let email = document.getElementById('email').value;
  let msg = document.getElementByClass('contact__form__textarea contact__form__inpt');
}
localStorage.setItem("form", JSON.stringify(form));
```
![Screenshot from 2023-06-22 22-35-31](https://github.com/Feliperto/PortfolioWebsite-Microverse/assets/46388113/6820a516-1901-426d-9b1a-29696e9eba02)

2023-06-22 23:41 UTC, shahadat3669 requested changes
Hi everone, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

<img src="https://media4.giphy.com/media/m3864rBwwBTKMAbpn3/giphy.gif"/>

 ## Highlights
✅  Good PR title
✅  Good PR description
✅  Good use of GitHub Flow


 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-22 23:41 UTC, shahadat3669 commented on js/main.js
> +const form = document.getElementById('contact__form')
- [ ] Well! I can see that you've made efforts to address the previous reviewer's update request. However, I noticed that when I fill out the form and click the submit button, if the submission is unsuccessful, the data is still being stored. 🔄 As per the project requirements, the data object should only be updated and saved to local storage when the user changes the content of any input field in the form not when click submit button.

Please ensure that your code follows the specified requirement and updates the data object and local storage only when there is a change in the form input fields.  Keep up the good work! 💪🌟

2023-06-23 15:30 UTC, AbeeraTahir approved these changes
# Status: Approved ✔️✔️✔️  

Hi team, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![approved](https://media.giphy.com/media/3ov9jSmllAIKuthAe4/giphy.gif)

## Highlights
✔️ Excellent implementation of the changes requested by the previous reviewers. 👍 

## Optional suggestions

N/A

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-23 15:32 UTC, merged